#sqlserver数据配置
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: 385878
#    url: jdbc:sqlserver://192.168.1.233:1433;DatabaseName=shiroTest
    username: sa
    password: mhsoft@888
    url: jdbc:sqlserver://192.168.1.220:1433;DatabaseName=LXSJERP
#    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: false
    hibernate:
      naming:
#        取消小写命名
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    #最大链接数
    max-connections: 5000
    #最大等待队列长度
    accept-count: 1000
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请请求体最大长度kb
    connection-timeout: 12000
    max-http-form-post-size: 2097152

